In [1]:
#import the numpy package under the name np

In [2]:
import numpy as np

In [3]:
#print the numpy version and the configuration
print(np.__version__)
np.show_config()

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ANKUSH RANA/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ANKUSH RANA/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ANKUSH RANA/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ANKUSH RANA/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ANKUSH RANA/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ANKUSH RANA/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ANKUSH RANA/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ANKUSH RANA/anaconda3\\Library\\include

In [4]:
#create a null vector of size 10
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
#How to get the documentation of the numpy add fuction from the command line?
import numpy; numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [9]:
#create a vector with values ranging from 10 to 49
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [14]:
#Reverse a vector (first element becomes last)
Z = np.arange(50)
print("before",Z)
Z = Z[::-1]
print("after",Z)

before [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
after [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [15]:
#Create a 3x3 matrix with values ranging from 0 to 8
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [18]:
#create a 3x3x3 array with random values
Z = np.random.random((3,3,3))
print(Z)

[[[0.14974959 0.61434799 0.28504053]
  [0.08950322 0.93845052 0.23355705]
  [0.96680881 0.60896321 0.74471527]]

 [[0.05004803 0.11216865 0.96516985]
  [0.4592458  0.31713145 0.14673638]
  [0.50777047 0.87067625 0.38329216]]

 [[0.21097313 0.02607976 0.45249127]
  [0.42833312 0.21442571 0.7606725 ]
  [0.40391403 0.48860442 0.63976923]]]


In [20]:
#create a random vector of size 30 and find the mean value
Z = np.random.random(30)
print(Z)
m = Z.mean()
print("mean value: ",m)

[0.21192517 0.9104652  0.80402434 0.91259775 0.36347865 0.81348631
 0.56634833 0.30095625 0.77002862 0.16974648 0.7751867  0.3825775
 0.92415102 0.79061685 0.08044213 0.90079276 0.03564244 0.32611321
 0.11616803 0.3254038  0.67606378 0.80767874 0.15279993 0.06540983
 0.39244671 0.52254705 0.64530003 0.64822833 0.42447693 0.3010415 ]
mean value:  0.5038714790769933


In [23]:
#create a 2d array with 1 on the border and 0 inside
Z = np.ones((10,10))
print(Z)
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [25]:
#what is the result of the following expession?
print(np.nan)
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)


nan
nan
False
False
nan
False


In [26]:
#Create a 5x5 martix with vales 1,2,3,4 just below the diagonal
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [27]:
#create a 8x8 matrix and fill with a checkerboard pattern
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [28]:
#Consider a (6,7,8) shape array,what is the index(x,y,z) of the 100th element?
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [30]:
#create a checkerboard 8x8 matrix using the tile function
Z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [31]:
#Normalize a 5x5 random matrix
Z = np.random.random((5,5))
print(Z)
Zmax, Zmin = Z.max(),Z.min()
print("Zmax",Z.max(),"and","Zmin",Z.min())
Z = (Z-Zmin)/(Zmax-Zmin)
print(Z)

[[0.56681778 0.07639145 0.53336014 0.44039397 0.46360045]
 [0.12750234 0.43003109 0.07057306 0.26858608 0.56293164]
 [0.85765124 0.94949915 0.03374359 0.99386857 0.44411626]
 [0.37163239 0.22904352 0.41496565 0.28943588 0.10087703]
 [0.056665   0.782698   0.67705452 0.40497639 0.81380967]]
Zmax 0.9938685690823613 and Zmin 0.033743589117385286
[[0.55521333 0.04441908 0.52036616 0.423539   0.44770927]
 [0.09765266 0.41274574 0.03835904 0.24459575 0.55116579]
 [0.85812542 0.95378787 0.         1.         0.42741588]
 [0.35192168 0.20341095 0.39705462 0.26631146 0.06992156]
 [0.02387337 0.78005929 0.67002833 0.3866505  0.81246306]]
